### ISSUE TITLE
Unable to parse an str slice into Address

### ISSUE THREAD

**Issue by fredfortier** [tomusdrw/rust-web3#131]
I'm running this example: `/Users/fredfortier/Code/sandbox/rust-web3/examples/contract.rs`

I'm getting an error here:
```rust
    let my_account: Address = "0x00a329c0648769a73afac7f9381e08fb43dbea72"
        .parse()
        .unwrap();
```

Here the error:
```
     Running `target/debug/examples/contract`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid character 'x' at position 1', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::begin_panic
             at libstd/panicking.rs:402
   5: std::panicking::try::do_call
             at libstd/panicking.rs:349
   6: std::panicking::try::do_call
             at libstd/panicking.rs:325
   7: core::ptr::drop_in_place
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10: contract::main
             at examples/contract.rs:13
  11: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  14: <std::io::Write::write_fmt::Adaptor<'a, T> as core::fmt::Write>::write_str
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  16: contract::main
```

**Comment by tomusdrw** [comment]
@fredfortier please remove `0x` from the string, parsing has changed in one of the libraries we depend on, but the examples were not updated (PRs welcome!)

**Comment by fredfortier** [comment]
@tomusdrw It worked. Yes, I'm happy to push a PR for this. I'll go through the examples and update them.
