### ISSUE TITLE
Assertion failed when calling a SmartContract

### ISSUE THREAD

**Issue by PhdTrollSlayer** [tomusdrw/rust-web3#223]
Code: 
``` rust
use web3::contract::{Contract, Options};
use web3::types::{Address, H160};
use web3::futures::Future;


pub fn submeter_revisao(end_servidor: &str, report: &str) {
    let (_eloop, transport) = web3::transports::Http::new("http://127.0.0.1:8545").unwrap();
    let web3 = web3::Web3::new(transport);

    let end_contrato: Address = "b4c79dab8f259c7aee6e5b2aa729821864227e84".parse().unwrap();
    let contract = Contract::from_json(web3.eth(), end_contrato, include_bytes!("../../solidity/store.abi")).unwrap();

    contract.call("set_report", report.to_string(), Address::from_slice(end_servidor.as_bytes()), Options::default());

    let result = contract.query("get_report", (), None, Options::default(), None);
    let result: String = result.wait().unwrap();

    println!("{}", result)
}
```

Output:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `40`,
 right: `20`', /home/rodrigo/.cargo/registry/src/github.com-1ecc6299db9ec823/ethereum-types-0.5.2/src/hash.rs:74:1
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by tomusdrw** [comment]
Can you enable `BACKTRACE` and show exactly where the error is? My guess is that you try to put hex-encoded string that represents `Address` and put it directly to the type using `Address::from_slice`, most likely here:
`Address::from_slice(end_servidor.as_bytes())`

**Comment by PhdTrollSlayer** [comment]
Backtrace:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `40`,
 right: `20`', /home/rodrigo/.cargo/registry/src/github.com-1ecc6299db9ec823/ethereum-types-0.5.2/src/hash.rs:74:1
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: ethereum_types::hash::H160::from_slice
             at /home/rodrigo/.cargo/registry/src/github.com-1ecc6299db9ec823/ethereum-types-0.5.2/<::fixed_hash::hash::construct_fixed_hash macros>:83
   8: blockcar_genesis::contract::report::submeter_revisao
             at src/contract/report.rs:13
   9: blockcar_genesis::main
             at src/main.rs:50
  10: std::rt::lang_start::{{closure}}
             at /rustc/372be4f360ce42b1a10126a711189796f8440ab4/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/372be4f360ce42b1a10126a711189796f8440ab4/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start
```

**Comment by tomusdrw** [comment]
Indeed, so if I count correctly, its because you are doing `Address::from_slice(end_servidor.as_bytes())`. The docs for `::from_slice` warn that it panics if given slide has incorrect length. Can you try this instead:
```
let end_servidor: Address = end_servidor.parse().expect("Invalid address given");
```
?

**Comment by tomusdrw** [comment]
Closing as resolved.
