### ISSUE TITLE
Rust Client Returns "Abi error: Invalid data"

### ISSUE THREAD

**Issue by creese** [tomusdrw/rust-web3#383]
I'm building a Rust client to interact with a smart contract on Ethereum. The contract works, but there seems to be an issue with the client.

I am building from this example:
https://github.com/tomusdrw/rust-web3/blob/master/examples/contract.rs

The contract has been deployed to Ganache and prepared via truffle console to the proper state. Running the client script should print a value of 100 (or the Wei equivalent). Instead, I get this:

`Abi error: Invalid data`. 

Here is the relevant portion of the ABI:
```
// --snip--
  {
    "inputs": [],
    "name": "balance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
// --snip--
```

The entire ABI is here:
https://gist.github.com/creese/5e50fac5ce680636bf969088fa4dd798

Here is the code:
```
// --snip--
#[tokio::main]
async fn get_balance(
    args: BalanceArgs,
    config_overrides: Option<Vec<(String, String)>>,
) -> Result<String, Box<dyn Error>> {

    let http = web3::transports::Http::new("http://127.0.0.1:7545")?;
    let web3 = web3::Web3::new(http);

    let from: Address = config_overrides
        .unwrap()
        .iter()
        .filter(|x| x.0 == "from")
        .collect::<Vec<_>>()[0]
        .1
        .parse()?;

    let to: Address = args.address.parse()?;

    let contract = Contract::from_json(
        web3.eth(),
        to,
        include_bytes!("../../target/contracts/abi/contract.abi"),
    )?;

    let result =
        contract.query("balance", (from,), None, Options::default(), None);
    let balance: U256 = result.await?;

    // The code never reaches here.

    Ok(balance.as_u32().to_string())
}
// --snip--
```

The error appears to be generated at or after the await. Do you have any suggestions as to what might be happening or the best way to troubleshoot?

**Comment by creese** [comment]
The contract was compiled with solc 0.6.12.

**Comment by creese** [comment]
I'm trying to remove Truffle from the workflow. This attempt deploys a bare bones smart contract using only solc and rust-web3. The Rust client is able to get all the accounts. However, the deploy do not succeed. The code, artifacts, and log output appear below.

contracts/src/HelloToken.sol
```
pragma solidity ^0.6.12;

contract HelloToken {
    uint public balance = 42;
}
```
```
$ solc -o target/contracts --bin --abi contracts/src/HelloToken.sol
```
target/contracts/HelloToken.abi:
```
[{"inputs":[],"name":"balance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}]
```
target/contracts/HelloToken.bin:
```
6080604052602a600055348015601457600080fd5b506085806100236000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b69ef8a814602d575b600080fd5b60336049565b6040518082815260200191505060405180910390f35b6000548156fea2646970667358221220bd3bcf1a8d2c0139257a074165e21c83e4d17f80549ad550ec329fceb2d361fd64736f6c634300060c0033
```
main.rs:
```
use std::process;

fn main() {

    let result = hello_contract::init();

    match result {
        Ok(s) => println!("{}", s),
        Err(e) => {
            eprintln!("fatal: {}", e);
            process::exit(1);
        }
    }
}
```

lib.rs:
```
#[macro_use]
extern crate log;

use std::error::Error;
use web3::contract::{Contract, Options};
use web3::types::U256;

#[tokio::main]
pub async fn init() -> Result<String, Box<dyn Error>> {
    env_logger::init();

    let http = web3::transports::Http::new("http://127.0.0.1:7545")?;
    let web3 = web3::Web3::new(http);

    let from = web3.eth().accounts().await?[0];

    debug!("from: {}", from);

    let bytecode = include_str!("../../target/contracts/HelloToken.bin");

    debug!("One");

    let contract = Contract::deploy(
        web3.eth(),
        include_bytes!("../../target/contracts/HelloToken.abi"),
    )?
    .confirmations(0)
    .options(Options::with(|opt| {
        opt.value = Some(5.into());
        opt.gas_price = Some(5.into());
        opt.gas = Some(3_000_000.into());
    }))
    .execute(bytecode, (), from)
    .expect("Correct parameters are passed to the constructor.")
    .await?;

    debug!("Two");

    let result =
        contract.query("balance", (from,), None, Options::default(), None);

    debug!("Three");

    let balance: U256 = result.await?;

    debug!("Four");

    Ok(balance.as_u64().to_string())
}
```
```
$ RUST_LOG=trace cargo run --
```
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `/home/hero/code/fundme/target/debug/fundme`
[2020-10-11T02:08:21Z DEBUG web3::transports::http] [1] Sending: {"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1} to http://127.0.0.1:7545/
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Request pending.
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T02:08:21Z TRACE hyper::client::pool] checkout waiting for idle connection: ("http", 127.0.0.1:7545) 
[2020-10-11T02:08:21Z TRACE hyper::client::connect::http] Http::connect; scheme=Some("http"), host=Some("127.0.0.1"), port=Some(Port(7545)) 
[2020-10-11T02:08:21Z DEBUG hyper::client::connect::http] connecting to 127.0.0.1:7545 
[2020-10-11T02:08:21Z TRACE mio::poll] registering with poller
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T02:08:21Z DEBUG hyper::client::connect::http] connected to 127.0.0.1:7545 
[2020-10-11T02:08:21Z TRACE hyper::client::conn] client handshake HTTP/1 
[2020-10-11T02:08:21Z TRACE hyper::client] handshake complete, spawning background dispatcher task 
[2020-10-11T02:08:21Z TRACE want] signal: Want
[2020-10-11T02:08:21Z TRACE want] signal found waiting giver, notifying
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy } 
[2020-10-11T02:08:21Z TRACE want] poll_want: taker wants!
[2020-10-11T02:08:21Z TRACE hyper::client::pool] checkout dropped for ("http", 127.0.0.1:7545) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] encode_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] -> encode_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] Client::encode method=POST, body=Some(Known(60)) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] <- encode_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] -- encode_headers
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::io] flushed 174 bytes 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy } 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] Conn::read_head 
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::io] read 637 bytes 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] parse_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] -> parse_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] Response.parse([Header; 100], [u8; 637]) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] Response.parse Complete(140) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] <- parse_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] -- parse_headers
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::io] parsed 4 headers 
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::conn] incoming body is chunked encoding 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] decode; state=Chunked(Size, 0) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Chunk size is 485 
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::decode] incoming chunked header: 0x1E5 (485 bytes) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Chunked read, remaining=485 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Body(Chunked(BodyCr, 0)), writing: KeepAlive, keep_alive: Busy } 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] decode; state=Chunked(BodyCr, 0) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Chunk size is 0 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] end of chunked 
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::conn] incoming body completed 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] maybe_notify; read_from_io blocked 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T02:08:21Z TRACE want] signal: Want
[2020-10-11T02:08:21Z TRACE want] signal found waiting giver, notifying
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle } 
[2020-10-11T02:08:21Z TRACE want] signal: Want
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle } 
[2020-10-11T02:08:21Z TRACE want] poll_want: taker wants!
[2020-10-11T02:08:21Z TRACE hyper::client::pool] put; add idle connection for ("http", 127.0.0.1:7545) 
[2020-10-11T02:08:21Z DEBUG hyper::client::pool] pooling idle connection for ("http", 127.0.0.1:7545) 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T02:08:21Z TRACE web3::transports::http] [1] Extracting result from:
    {"id":1,"jsonrpc":"2.0","result":["0x76d8872a515f50c4be2017b2ed5d949773fd2679","0x20e7a060c336c28b1054034b10dde6859900020f","0x7e4d5ab6ca05d9bbdef7dd9e64a2d7b6145d2f78","0x46f63c90a74e935572e4c2e52357d881319a94f4","0x5deb96547e76342e34e369162e07a1244af38b74","0x689969a66b5d0900d4a5a13ca830f17f7ba42df4","0x96dc217c2eb07515c2af5436443ab5041d8182ff","0xc2c067961ea552b1547cc5877e1b9e055082b3dc","0x8732aa5253b2ffa97291b75652e3e23c544cdfb9","0xa6e7e0ccfb6b0f971cbe2e52662f6895c3c8ea0d"]}
[2020-10-11T02:08:21Z DEBUG fundme] from: 0x76d8…2679
[2020-10-11T02:08:21Z TRACE want] signal: Want
[2020-10-11T02:08:21Z DEBUG fundme] One
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle } 
[2020-10-11T02:08:21Z DEBUG web3::transports::http] [2] Sending: {"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"data":"0x6080604052602a600055348015601457600080fd5b506085806100236000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b69ef8a814602d575b600080fd5b60336049565b6040518082815260200191505060405180910390f35b6000548156fea2646970667358221220bd3bcf1a8d2c0139257a074165e21c83e4d17f80549ad550ec329fceb2d361fd64736f6c634300060c0033","from":"0x76d8872a515f50c4be2017b2ed5d949773fd2679","gas":"0x2dc6c0","gasPrice":"0x5","value":"0x5"}],"id":2} to http://127.0.0.1:7545/
[2020-10-11T02:08:21Z TRACE web3::transports::http] [2] Request pending.
[2020-10-11T02:08:21Z TRACE web3::transports::http] [2] Checking response.
[2020-10-11T02:08:21Z TRACE hyper::client::pool] take? ("http", 127.0.0.1:7545): expiration = Some(90s) 
[2020-10-11T02:08:21Z DEBUG hyper::client::pool] reuse idle connection for ("http", 127.0.0.1:7545) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] encode_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] -> encode_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] Client::encode method=POST, body=Some(Known(516)) 
[2020-10-11T02:08:21Z TRACE hyper::client::pool] idle interval checking for expired 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] <- encode_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] -- encode_headers
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::io] flushed 631 bytes 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy } 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] Conn::read_head 
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::io] read 971 bytes 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] parse_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] -> parse_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] Response.parse([Header; 100], [u8; 971]) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] Response.parse Complete(140) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] <- parse_headers
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::role] -- parse_headers
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::io] parsed 4 headers 
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::conn] incoming body is chunked encoding 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] decode; state=Chunked(Size, 0) 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [2] Checking response.
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Chunk size is 819 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [2] Reading body.
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::decode] incoming chunked header: 0x333 (819 bytes) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Chunked read, remaining=819 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [2] Reading body.
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Body(Chunked(BodyCr, 0)), writing: KeepAlive, keep_alive: Busy } 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [2] Reading body.
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] decode; state=Chunked(BodyCr, 0) 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Read chunk hex size 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] Chunk size is 0 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::decode] end of chunked 
[2020-10-11T02:08:21Z DEBUG hyper::proto::h1::conn] incoming body completed 
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] maybe_notify; read_from_io blocked 
[2020-10-11T02:08:21Z TRACE want] signal: Want
[2020-10-11T02:08:21Z TRACE want] signal found waiting giver, notifying
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle } 
[2020-10-11T02:08:21Z TRACE want] signal: Want
[2020-10-11T02:08:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle } 
[2020-10-11T02:08:21Z TRACE want] poll_want: taker wants!
[2020-10-11T02:08:21Z TRACE hyper::client::pool] put; add idle connection for ("http", 127.0.0.1:7545) 
[2020-10-11T02:08:21Z DEBUG hyper::client::pool] pooling idle connection for ("http", 127.0.0.1:7545) 
[2020-10-11T02:08:21Z TRACE web3::transports::http] [2] Reading body.
[2020-10-11T02:08:21Z TRACE web3::transports::http] [2] Extracting result from:
    {"id":2,"jsonrpc":"2.0","result":"0xac17b8ae2ed37cf36b73056b5a2bc88a1666bae9ff43162d9548f077b17f155b","error":{"message":"VM Exception while processing transaction: revert","code":-32000,"data":{"0xac17b8ae2ed37cf36b73056b5a2bc88a1666bae9ff43162d9548f077b17f155b":{"error":"revert","program_counter":20,"return":"0x"},"stack":"RuntimeError: VM Exception while processing transaction: revert\n    at Function.RuntimeError.fromResults (/tmp/.mount_ganachWyLePF/resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:89:13)\n    at BlockchainDouble.processBlock (/tmp/.mount_ganachWyLePF/resources/static/node/node_modules/ganache-core/lib/blockchain_double.js:632:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","name":"RuntimeError"}}}
[2020-10-11T02:08:21Z TRACE mio::poll] deregistering handle with poller
[2020-10-11T02:08:21Z TRACE want] signal: Closed
fatal: Api error: Got invalid response: Error("data did not match any variant of untagged enum Response", line: 0, column: 0)
```

**Comment by tomusdrw** [comment]
@creese Isn't Solidity constructor non-payable by default? Have you tried deploying with `value = 0` or adding an explicitly payable constructor?

**Comment by creese** [comment]
I set `value` equal to zero. (Thanks for that.) The contract appears to deploy but the query still fails. I seem to be back to "Abi error: Invalid data".

```
$ RUST_LOG="web3=trace,hello_token=debug" cargo run --
```
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `/home/******/hello_token/target/debug/hello_token`
[2020-10-11T05:32:37Z DEBUG web3::transports::http] [1] Sending: {"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1} to http://127.0.0.1:7545/
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Request pending.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [1] Extracting result from:
    {"id":1,"jsonrpc":"2.0","result":["0x76d8872a515f50c4be2017b2ed5d949773fd2679","0x20e7a060c336c28b1054034b10dde6859900020f","0x7e4d5ab6ca05d9bbdef7dd9e64a2d7b6145d2f78","0x46f63c90a74e935572e4c2e52357d881319a94f4","0x5deb96547e76342e34e369162e07a1244af38b74","0x689969a66b5d0900d4a5a13ca830f17f7ba42df4","0x96dc217c2eb07515c2af5436443ab5041d8182ff","0xc2c067961ea552b1547cc5877e1b9e055082b3dc","0x8732aa5253b2ffa97291b75652e3e23c544cdfb9","0xa6e7e0ccfb6b0f971cbe2e52662f6895c3c8ea0d"]}
[2020-10-11T05:32:37Z DEBUG hello_token] from: 0x76d8…2679
[2020-10-11T05:32:37Z DEBUG hello_token] One
[2020-10-11T05:32:37Z DEBUG web3::transports::http] [2] Sending: {"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"data":"0x6080604052602a600055348015601457600080fd5b506085806100236000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b69ef8a814602d575b600080fd5b60336049565b6040518082815260200191505060405180910390f35b6000548156fea2646970667358221220bd3bcf1a8d2c0139257a074165e21c83e4d17f80549ad550ec329fceb2d361fd64736f6c634300060c0033","from":"0x76d8872a515f50c4be2017b2ed5d949773fd2679","gas":"0x2dc6c0","gasPrice":"0x5","value":"0x0"}],"id":2} to http://127.0.0.1:7545/
[2020-10-11T05:32:37Z TRACE web3::transports::http] [2] Request pending.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [2] Checking response.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [2] Checking response.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [2] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [2] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [2] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [2] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [2] Extracting result from:
    {"id":2,"jsonrpc":"2.0","result":"0x080137e7e4ea8d195bc0b3ce5165d1169f4d77f70f5b8ff6a8df33175300f771"}
[2020-10-11T05:32:37Z DEBUG web3::transports::http] [3] Sending: {"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x080137e7e4ea8d195bc0b3ce5165d1169f4d77f70f5b8ff6a8df33175300f771"],"id":3} to http://127.0.0.1:7545/
[2020-10-11T05:32:37Z TRACE web3::transports::http] [3] Request pending.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [3] Checking response.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [3] Checking response.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [3] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [3] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [3] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [3] Reading body.
[2020-10-11T05:32:37Z TRACE web3::transports::http] [3] Extracting result from:
    {"id":3,"jsonrpc":"2.0","result":{"transactionHash":"0x080137e7e4ea8d195bc0b3ce5165d1169f4d77f70f5b8ff6a8df33175300f771","transactionIndex":"0x0","blockHash":"0xf0f510b6b7d16c203d2fe03bcb14b0aadf8de5e01f6fccea20a4b8cef513c9e8","blockNumber":"0x7","from":"0x76d8872a515f50c4be2017b2ed5d949773fd2679","to":null,"gasUsed":"0x18f63","cumulativeGasUsed":"0x18f63","contractAddress":"0xa6ee17286f33c6eeb1d3eb468242a1207703ea1b","logs":[],"status":"0x1","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}}
[2020-10-11T05:32:37Z DEBUG hello_token] Two
[2020-10-11T05:32:37Z DEBUG hello_token] Three
fatal: Abi error: Invalid data
```

**Comment by tomusdrw** [comment]
@creese I don't see the query being made in the logs, I suspect the RPC response is `0x` or something.
Are you sure that with `0` confirmations the contract is actually deployed before the `contract.query` RPC call is being made? No contract yet would explain incorrect response.

**Comment by creese** [comment]
No, I'm not sure the contract is deployed. When I set `confirmations` equal to `1`, the script never finishes.

**Comment by creese** [comment]
Unfortunately, I can't show the logs. There is an unrelated issue with Ganache. It doesn't let me set a log file directory.

**Comment by creese** [comment]
This is the value of `contract` with zero confirmations:
```
Contract {
    address: 0x50dda367285f6fb12eb647947bce5ca4ced8fa36,
    eth: Eth {
        transport: Http {
            id: 4,
            url: http://127.0.0.1:7545/,
            basic_auth: None,
            client: Client,
        },
    },
    abi: Contract {
        constructor: None,
        functions: {
            "balance": [
                Function {
                    name: "balance",
                    inputs: [],
                    outputs: [
                        Param {
                            name: "",
                            kind: Uint(
                                256,
                            ),
                        },
                    ],
                    constant: false,
                },
            ],
        },
        events: {},
        fallback: false,
    },
}
```
When I set `confirmations` equal to one, the future never completes and the value of `contract` is never printed.

**Comment by creese** [comment]
Here are the logs following the request to get the account addresses:
```
[11:51:56 PM] eth_sendTransaction
[11:51:56 PM] eth_sendTransaction
[11:51:56 PM]    > {
[11:51:56 PM]    >   "jsonrpc": "2.0",
[11:51:56 PM]    >   "method": "eth_sendTransaction",
[11:51:56 PM]    >   "params": 
[
[11:51:56 PM]    >     {
[11:51:56 PM]    >       "data": "0x6080604052602a600055348015601457600080fd5b506085806100236000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b69ef8a814602d575b600080fd5b60336049565b6040518082815260200191505060405180910390f35b6000548156fea2646970667358221220bd3bcf1a8d2c0139257a074165e21c83e4d17f80549ad550ec329fceb2d361fd64736f6c634300060c0033",
[11:51:56 PM]    >       "from": "0x76d8872a515f50c4be2017b2ed5d949773fd2679",
[11:51:56 PM]    >       "gas": "0x2dc6c0",
[11:51:56 PM]    >       "gasPrice": "0x5",
[11:51:56 PM]    >       "value": "0x0"
[11:51:56 PM]    >     }
[11:51:56 PM]    >   ],
[11:51:56 PM]    >   "id": 2
[11:51:56 PM]    > }
[11:51:56 PM]  <   {
[11:51:56 PM]  <     "id": 2,
[11:51:56 PM]  <     "jsonrpc": "2.0",
[11:51:56 PM]  <     "result": "0x85ed6f80083fb22e6ba9c792a19fe242b0ff4c48fc9da0468e2cc54ea721c099"
[11:51:56 PM]  <   }
[11:51:56 PM] 
[11:51:56 PM]   Transaction: 0x85ed6f80083fb22e6ba9c792a19fe242b0ff4c48fc9da0468e2cc54ea721c099
[11:51:56 PM]   Contract created: 0x592c62623a44f1258b4f5c3671758796fd5a4ad6
[11:51:56 PM]   Gas usage: 102243
[11:51:56 PM]   Block Number: 15
[11:51:56 PM]   Block Time: Sat Oct 10 2020 23:51:56 GMT-0700 (Pacific Daylight Time)
```

**Comment by creese** [comment]
This function queries a hard-coded contract address without deploying:

lib.rs:
```
#[tokio::main]
pub async fn init() -> Result<String, Box<dyn Error>> {
    env_logger::init();

    let http = web3::transports::Http::new("http://127.0.0.1:7545")?;
    let web3 = web3::Web3::new(http);

    let from = web3.eth().accounts().await?[0];

    debug!("from: {}", from);

    let bytecode = include_str!("../../target/contracts/HelloToken.bin");

    debug!("One");

    let contract = Contract::deploy(
        web3.eth(),
        include_bytes!("../../target/contracts/HelloToken.abi"),
    )?
    .confirmations(1)
    .options(Options::with(|opt| {
        opt.value = Some(0.into());
        opt.gas_price = Some(5.into());
        opt.gas = Some(3_000_000.into());
    }))
    .execute(bytecode, (), from)
    .expect("Correct parameters are passed to the constructor.")
    .await?;

    debug!("Two");

    println!("{:#?}", contract);

    let result =
        contract.query("balance", (from,), None, Options::default(), None);

    debug!("Three");

    let balance: U256 = result.await?;

    debug!("Four");

    Ok(balance.as_u64().to_string())
}
```
```
$ RUST_LOG="web3=trace,fundme=debug" cargo run --
```
```
   Compiling hello_token v0.1.0 (/home/******/hello_token/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 5.81s
     Running `target/debug/hello_token`
[2020-10-11T07:11:17Z DEBUG web3::transports::http] [1] Sending: {"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1} to http://127.0.0.1:7545/
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Request pending.
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Checking response.
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Reading body.
[2020-10-11T07:11:17Z TRACE web3::transports::http] [1] Extracting result from:
    {"id":1,"jsonrpc":"2.0","result":["0x76d8872a515f50c4be2017b2ed5d949773fd2679","0x20e7a060c336c28b1054034b10dde6859900020f","0x7e4d5ab6ca05d9bbdef7dd9e64a2d7b6145d2f78","0x46f63c90a74e935572e4c2e52357d881319a94f4","0x5deb96547e76342e34e369162e07a1244af38b74","0x689969a66b5d0900d4a5a13ca830f17f7ba42df4","0x96dc217c2eb07515c2af5436443ab5041d8182ff","0xc2c067961ea552b1547cc5877e1b9e055082b3dc","0x8732aa5253b2ffa97291b75652e3e23c544cdfb9","0xa6e7e0ccfb6b0f971cbe2e52662f6895c3c8ea0d"]}
[2020-10-11T07:11:17Z DEBUG hello_token] from: 0x76d8…2679
[2020-10-11T07:11:17Z DEBUG hello_token] to: 0x592c62623a44f1258b4f5c3671758796fd5a4ad6
Contract {
    address: 0x592c62623a44f1258b4f5c3671758796fd5a4ad6,
    eth: Eth {
        transport: Http {
            id: 2,
            url: http://127.0.0.1:7545/,
            basic_auth: None,
            client: Client,
        },
    },
    abi: Contract {
        constructor: None,
        functions: {
            "balance": [
                Function {
                    name: "balance",
                    inputs: [],
                    outputs: [
                        Param {
                            name: "",
                            kind: Uint(
                                256,
                            ),
                        },
                    ],
                    constant: false,
                },
            ],
        },
        events: {},
        fallback: false,
    },
}
[2020-10-11T07:11:17Z DEBUG hello_token] One
[2020-10-11T07:11:17Z DEBUG hello_token] Two
fatal: Abi error: Invalid data
```

**Comment by creese** [comment]
I got it work. The arguments to `contract.query()` were wrong. 

For my contract, the correct invocation is:
```
let result = contract.query("balance", (), None, Options::default(), None);
```

**Comment by tomusdrw** [comment]
Ah, good catch, I didn't see that. I think we could detect in the ABI that the function doesn't expect any parameters and warn (or even error out) if the user tries to pass a non-empty parameter list, wdyt?

**Comment by creese** [comment]
Absolutely! If we can compare the full type signature that would be even better.
