### ISSUE TITLE
Cannot run example: receipt can't be null after wait for confirmations

### ISSUE THREAD

**Issue by stnbu** [tomusdrw/rust-web3#523]
I have ganache-cli running with the correct seed words per the README file. When I run the example it complains:

```
$ cargo run --example contract
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/examples/contract`
thread 'main' panicked at 'receipt can't be null after wait for confirmations; qed', /Users/mburr/git/rust-web3/src/confirm.rs:88:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1321:5
   3: core::option::Option<T>::expect
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:349:21
   4: web3::confirm::send_transaction_with_confirmation_::{{closure}}
             at ./src/confirm.rs:85:19
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/future/mod.rs:80:19
   6: web3::confirm::send_transaction_with_confirmation::{{closure}}
             at ./src/confirm.rs:103:5
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/future/mod.rs:80:19
   8: web3::contract::deploy::Builder<T>::do_execute::{{closure}}
             at ./src/contract/deploy.rs:212:23
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/future/mod.rs:80:19
  10: web3::contract::deploy::Builder<T>::execute::{{closure}}
             at ./src/contract/deploy.rs:58:9
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/future/mod.rs:80:19
  12: contract::main::{{closure}}
             at ./examples/contract.rs:17:20
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/future/mod.rs:80:19
  14: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/mburr/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/park/thread.rs:263:54
  15: tokio::coop::with_budget::{{closure}}
             at /Users/mburr/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:106:9
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/thread/local.rs:272:16
  17: std::thread::local::LocalKey<T>::with
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/thread/local.rs:248:9
  18: tokio::coop::with_budget
             at /Users/mburr/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:99:5
  19: tokio::coop::budget
             at /Users/mburr/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:76:5
  20: tokio::park::thread::CachedParkThread::block_on
             at /Users/mburr/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/park/thread.rs:263:31
  21: tokio::runtime::enter::Enter::block_on
             at /Users/mburr/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/enter.rs:151:13
  22: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/mburr/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/mod.rs:71:9
  23: tokio::runtime::Runtime::block_on
             at /Users/mburr/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/mod.rs:452:43
  24: contract::main
             at ./examples/contract.rs:49:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:227:5
```

If I set confirmations from `0` to `1` [here](https://github.com/tomusdrw/rust-web3/blob/d0315eb768c90b9663f47c38b61662085a19f22a/examples/contract.rs#L18), I encounter a different problem:

```
   Compiling web3 v0.16.0 (/Users/mburr/git/rust-web3)
    Finished dev [unoptimized + debuginfo] target(s) in 4.17s
     Running `target/debug/examples/contract`
Error: Deployment(ContractDeploymentFailure(0xc7e5a181ca1b55f6e5e7d47bfc2650034144ed61e9d1eb9bde4652f9c0c9b781))
```

The ganache console output looks like this (running the above two in succession):

```
Ganache CLI v6.12.2 (ganache-core: 2.13.2)

Available Accounts
==================
(0) 0xd028D24F16A8893bd078259D413372aC01580769 (100 ETH)
(1) 0x75DF5695686338883675bB27BD06fC7578aA01b7 (100 ETH)
(2) 0xbC1057A3Bb7A5650D4bE05F74837f872C1174E4c (100 ETH)
(3) 0x77c7f75a99776bf1cFff0F025D8b2BE91770808e (100 ETH)
(4) 0xA7dcb1F21e7381fBA480F3D0eaB034905Aa9a7a7 (100 ETH)
(5) 0x341E8055aa00f26EA593A84c6E634087F89e2DBc (100 ETH)
(6) 0xa36f853727639d260a533B4694D1f3Fd95C5e2a8 (100 ETH)
(7) 0x2f2caC8DeBA4ac9236dBDc807EA2A662fe97169d (100 ETH)
(8) 0xD77342b127aE0eb2d73A8bCf8cb34E9E9dF8Be3B (100 ETH)
(9) 0xAB4b65661c2E6061321ab68Dd2741132F41D3d19 (100 ETH)

Private Keys
==================
(0) 0x90b1498fcac1911f91cd650dd4091b36d32e728eb8c5be611af35e3d3e04dd7d
(1) 0xf07dad2c3dad6a50b68fefb0b776397a4d586dea7ad91ea41bc5373ec820dd41
(2) 0x916eee3dae838c219c2d6c96f2cf75fd54eccc79b5bc1f4be63c2c794f4357d0
(3) 0xe201f343b3f20b3d6ba88a22d49756ae1fdec5d14345a7af8dd19a80ca6cd2a4
(4) 0x17666b0097c69ee7cc842b9760c231b3a2ccbd787e96c7c9fc348ab8bb4bd8a6
(5) 0xe262320406165920a2dd3bfd8a820406a96ecf8a617ecd1d3d9e88b068cea586
(6) 0xf8f69e058ae0533f5b0880532cd03a86cf09e8bf43ef2cb03b6d10f88a6e2e14
(7) 0xc1ff9c6333943802e123af8d18bcbd8371ba2d9a845b2406755178c982d26db2
(8) 0x97ca797cf9a2b03ccf622899d7ffa6d418974bc2963bdd5b2e680c3b8a384c38
(9) 0xaa1ca47095c741e5903e1472340c7501f2b740695b81aafe8a6f54446e6def25

HD Wallet
==================
Mnemonic:      hamster coin cup brief quote trick stove draft hobby strong caught unable
Base HD Path:  m/44'/60'/0'/0/{account_index}

Gas Price
==================
20000000000

Gas Limit
==================
6721975

Call Gas Limit
==================
9007199254740991

Listening on 127.0.0.1:8545
eth_sendTransaction
eth_getTransactionReceipt

  Transaction: 0x43de95eee57c659443f8635a5ac5d708d7e916ee57f41f97897504c0ae214443
  Contract created: 0x4d470146215d085c75767b717dbb8d3b4468f893
  Gas usage: 114875
  Block Number: 12
  Block Time: Fri Jul 16 2021 11:51:56 GMT-0600 (Mountain Daylight Time)
  Runtime Error: revert

eth_sendTransaction
eth_newBlockFilter

  Transaction: 0x38f55048829a72d9d821cea415c8899f24dee5895ceddede686463d7f8dd32f7
  Contract created: 0xec0b9ed45c0357a4539df79ba7cf1259a2cf4add
  Gas usage: 114875
  Block Number: 31
  Block Time: Fri Jul 16 2021 11:52:54 GMT-0600 (Mountain Daylight Time)
  Runtime Error: revert

eth_getFilterChanges
eth_getTransactionReceipt
eth_blockNumber
eth_getTransactionReceipt
```

## Envoronment

```
$ git pull && git rev-parse HEAD
Already up to date.
d0315eb768c90b9663f47c38b61662085a19f22a
```
```
$ cargo --version
cargo 1.52.0 (69767412a 2021-04-21)
```
```
$ rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)
```

A side note: I also encounter #432 with the above environment. I can just trim the newline from `examples/res/contract_token.code` and all is fine. I'll see if I can come up with a general fix.

**Comment by tomusdrw** [comment]
I haven't been looking into Solidity examples, but perhaps the bytecode is a bit outdated now?

**Comment by stnbu** [comment]
I'll be trying some recompiling and experimentation.

**Comment by stnbu** [comment]
Here's a data point: I changed the code thusly...

```
diff --git a/examples/contracts/SimpleEvent.sol b/examples/contracts/SimpleEvent.sol
index edfd4b5..b7bdb4e 100644
--- a/examples/contracts/SimpleEvent.sol
+++ b/examples/contracts/SimpleEvent.sol
@@ -1,4 +1,4 @@
-pragma solidity ^0.4.0;
+pragma solidity ^0.8.0;

 contract SimpleEvent {
     event Hello(address sender);
diff --git a/examples/contracts/SimpleStorage.sol b/examples/contracts/SimpleStorage.sol
index 09e4562..665c720 100644
--- a/examples/contracts/SimpleStorage.sol
+++ b/examples/contracts/SimpleStorage.sol
@@ -1,13 +1,13 @@
-pragma solidity ^0.4.0;
+pragma solidity ^0.8.0;

 contract SimpleStorage {
     uint storedData;

-    function set(uint x) {
+    function set(uint x) public {
         storedData = x;
     }

-    function get() constant returns (uint) {
+    function get() public view returns (uint) {
         return storedData;
     }
 }
```

Compiled and put the `.abi` and `.bin` files in the right place, and still get the same error:

```
thread 'main' panicked at 'receipt can't be null after wait for confirmations; qed'
```

I wouldn't expect it to matter, but I used: `solcjs -o res --bin --abi contracts/*.sol` (moving the output files by hand).

```
$ solcjs --version
0.8.6+commit.11564f7e.Emscripten.clang
```
